### ISSUE TITLE
Prefers .htm to .html

### ISSUE THREAD

**Issue by hildjj** [o-p-n/serveit#39]
The results of this glob are in sorted order, not preferenced by the order in the glob string.  So if you have both file types, .htm is preferred.  That might be intended or not.

https://github.com/o-p-n/serveit/blob/152c4566d68504350b2de8cac2037c98f20125e6/src/file-entry.ts#L89

If 'index.html' is a directory, this call:

https://github.com/o-p-n/serveit/blob/152c4566d68504350b2de8cac2037c98f20125e6/src/file-entry.ts#L97

Will load index.html/index.html (etc.) which is a little surprising.

Combining both of those, you might have index.htm/ as a directory and a valid index.html file, and the valid .html file will be ignored, since you don't check the whole list returned from the glob.

**Comment by linuxwolf** [comment]
Great catch.

The intent was to prefer `.html` over `.htm`.  Also meant to only look for `index.{html,htm}` files and exclude directories.
