### ISSUE TITLE
Can etags be comma-separated?

### ISSUE THREAD

**Issue by hildjj** [o-p-n/serveit#40]
My reading of [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) says no, but maybe there's something I've missed.

https://github.com/o-p-n/serveit/blob/152c4566d68504350b2de8cac2037c98f20125e6/src/file-entry.ts#L61

**Comment by linuxwolf** [comment]
These come from the client via the [If-None-Match](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match) header, which is comma-separated.

**Comment by hildjj** [comment]
Is there a spec that says this, or is this just observed?

**Comment by linuxwolf** [comment]
[RFC9110](https://httpwg.org/specs/rfc9110.html#field.if-none-match)
