### ISSUE TITLE
commas in etag

### ISSUE THREAD

**Issue by hildjj** [o-p-n/serveit#48]
Commas (U+002c) are allowed in etags, and are matched by your regex... after you split on commas.

`"foo,bar"` is valid but will fail.  I don't think `*` is very useful for GET, but should you handle it anyway?

https://github.com/o-p-n/serveit/blob/152c4566d68504350b2de8cac2037c98f20125e6/src/file-entry.ts#L64

(follow-up to #40)

**Comment by linuxwolf** [comment]
I appreciate the calloout, but this isn't worth the effort.

The ETags are a best-effort network optimization, and this implementation generates ETags with only the hexidecimal alphabet of a fixed length.
